from typing import *

JSONValue = Union[str, int, float, bool, None, 'JSONObject', 'JSONArray']


class JSONObject:
    def __setitem__(self, k: str, v: JSONValue) -> None: ...
    def __delitem__(self, v: str) -> None: ...
    def __getitem__(self, k: str) -> JSONValue: ...
    def __iter__(self) -> Iterator[str]: ...


class JSONArray:
    def insert(self, index: int, value: JSONValue) -> None: ...
    def __getitem__(self, i: int) -> JSONValue: ...
    def __setitem__(self, i: int, o: JSONValue) -> None: ...
    def __delitem__(self, i: int) -> None: ...
